ARG APP_HOME=/usr/src/app

# build stage
FROM node:14.17 as build
WORKDIR ${APP_HOME}
COPY [ "package.json", "tsconfig.json", "yarn.lock", "./" ]
RUN yarn install
COPY . .
RUN yarn build

# deploy stage
FROM nginx:alpine
COPY --from=build ${APP_HOME}/build /usr/share/nginx/html
COPY --from=build ${APP_HOME}/build /var/www
COPY ./nginx /etc/nginx/conf.d/

WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]