default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["MYSQL_USERNAME"] || "app" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "password" %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  port: <%= ENV["MYSQL_PORT"] || "3306" %>

development:
  <<: *default
  database: appdb

test:
  <<: *default
  database: appdb_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
